[theme]
primaryColor = "#147d64"
backgroundColor = "#f7faf9"
secondaryBackgroundColor = "#edf3f0"
textColor = "#172e28"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
fileWatcherType = "none"
